image:
  file: .gitpod.dockerfile

ports:
  - port: 9980
    onOpen: ignore
  - port: 6080
    protocol: "http"
  - port: 5900
    onOpen: ignore

vscode:
  extensions:
    - ms-vscode.cpptools@0.26.2:Pq/tmf2WN3SanVzB4xZc1g==

